import { Changelog } from "@/components/features/pxl/marketing/changelog";
import type { Document } from "@/lib/schemas/pxl/changelog";

const changelog: Document = {
  title: "Changelog",
  description: `All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).`,
  versions: [
    {
      version: null,
      title: "[Unreleased]",
      date: null,
      body: "",
      parsed: {
        _: [],
      },
    },
    {
      version: "1.1.2",
      title: "[1.1.2] - 2024-09-27",
      date: "2024-09-27",
      body: "### Added\n\n- v1.1 German translation.\n- v1.1 Italian translation.\n- v1.1 Simplified Chinese translation.\n- v1.1 Persian translation.\n- v1.1 Polish translation.\n- v1.1 Slovenian translation.\n- v1.1 Traditional Chinese translation.\n- v1.1 Spanish translation.\n- v1.1 Brazilian Portuguese translation.\n- v1.1 Czech translation.\n- v1.1 Romanian translation.\n- v1.1 Swedish translation.\n- v1.1 Ukrainian translation.\n- v1.1 Korean translation.\n- v1.1 Indonesian translation.\n\n### Fixed\n\n- Improve French translation.\n- Improve Dutch translation.",
      parsed: {
        _: [
          "v1.1 German translation.",
          "v1.1 Italian translation.",
          "v1.1 Simplified Chinese translation.",
          "v1.1 Persian translation.",
          "v1.1 Polish translation.",
          "v1.1 Slovenian translation.",
          "v1.1 Traditional Chinese translation.",
          "v1.1 Spanish translation.",
          "v1.1 Brazilian Portuguese translation.",
          "v1.1 Czech translation.",
          "v1.1 Romanian translation.",
          "v1.1 Swedish translation.",
          "v1.1 Ukrainian translation.",
          "v1.1 Korean translation.",
          "v1.1 Indonesian translation.",
          "Improve French translation.",
          "Improve Dutch translation.",
        ],
        Added: [
          "v1.1 German translation.",
          "v1.1 Italian translation.",
          "v1.1 Simplified Chinese translation.",
          "v1.1 Persian translation.",
          "v1.1 Polish translation.",
          "v1.1 Slovenian translation.",
          "v1.1 Traditional Chinese translation.",
          "v1.1 Spanish translation.",
          "v1.1 Brazilian Portuguese translation.",
          "v1.1 Czech translation.",
          "v1.1 Romanian translation.",
          "v1.1 Swedish translation.",
          "v1.1 Ukrainian translation.",
          "v1.1 Korean translation.",
          "v1.1 Indonesian translation.",
        ],
        Fixed: ["Improve French translation.", "Improve Dutch translation."],
      },
    },
    {
      version: "1.1.1",
      title: "[1.1.1] - 2023-03-05",
      date: "2023-03-05",
      body: '### Added\n\n- v1.1 Arabic translation.\n- v1.1 French translation.\n- v1.1 Dutch translation.\n- v1.1 Russian translation.\n- v1.1 Japanese translation.\n- v1.1 Norwegian Bokmål translation.\n- v1.1 "Inconsistent Changes" Turkish translation.\n- Default to most recent versions available for each languages.\n- Display count of available translations (26 to date!).\n- Centralize all links into `/data/links.json` so they can be updated easily.\n\n### Fixed\n\n- Improve French translation.\n- Improve id-ID translation.\n- Improve Persian translation.\n- Improve Russian translation.\n- Improve Swedish title.\n- Improve zh-CN translation.\n- Improve French translation.\n- Improve zh-TW translation.\n- Improve Spanish (es-ES) transltion.\n- Foldout menu in Dutch translation.\n- Missing periods at the end of each change.\n- Fix missing logo in 1.1 pages.\n- Display notice when translation isn\'t for most recent version.\n- Various broken links, page versions, and indentations.\n\n### Changed\n\n- Upgrade dependencies: Ruby 3.2.1, Middleman, etc.\n\n### Removed\n\n- Unused normalize.css file.\n- Identical links assigned in each translation file.\n- Duplicate index file for the english version.',
      parsed: {
        _: [
          "v1.1 Arabic translation.",
          "v1.1 French translation.",
          "v1.1 Dutch translation.",
          "v1.1 Russian translation.",
          "v1.1 Japanese translation.",
          "v1.1 Norwegian Bokmål translation.",
          'v1.1 "Inconsistent Changes" Turkish translation.',
          "Default to most recent versions available for each languages.",
          "Display count of available translations (26 to date!).",
          "Centralize all links into /data/links.json so they can be updated easily.",
          "Improve French translation.",
          "Improve id-ID translation.",
          "Improve Persian translation.",
          "Improve Russian translation.",
          "Improve Swedish title.",
          "Improve zh-CN translation.",
          "Improve French translation.",
          "Improve zh-TW translation.",
          "Improve Spanish (es-ES) transltion.",
          "Foldout menu in Dutch translation.",
          "Missing periods at the end of each change.",
          "Fix missing logo in 1.1 pages.",
          "Display notice when translation isn't for most recent version.",
          "Various broken links, page versions, and indentations.",
          "Upgrade dependencies: Ruby 3.2.1, Middleman, etc.",
          "Unused normalize.css file.",
          "Identical links assigned in each translation file.",
          "Duplicate index file for the english version.",
        ],
        Added: [
          "v1.1 Arabic translation.",
          "v1.1 French translation.",
          "v1.1 Dutch translation.",
          "v1.1 Russian translation.",
          "v1.1 Japanese translation.",
          "v1.1 Norwegian Bokmål translation.",
          'v1.1 "Inconsistent Changes" Turkish translation.',
          "Default to most recent versions available for each languages.",
          "Display count of available translations (26 to date!).",
          "Centralize all links into /data/links.json so they can be updated easily.",
        ],
        Fixed: [
          "Improve French translation.",
          "Improve id-ID translation.",
          "Improve Persian translation.",
          "Improve Russian translation.",
          "Improve Swedish title.",
          "Improve zh-CN translation.",
          "Improve French translation.",
          "Improve zh-TW translation.",
          "Improve Spanish (es-ES) transltion.",
          "Foldout menu in Dutch translation.",
          "Missing periods at the end of each change.",
          "Fix missing logo in 1.1 pages.",
          "Display notice when translation isn't for most recent version.",
          "Various broken links, page versions, and indentations.",
        ],
        Changed: ["Upgrade dependencies: Ruby 3.2.1, Middleman, etc."],
        Removed: [
          "Unused normalize.css file.",
          "Identical links assigned in each translation file.",
          "Duplicate index file for the english version.",
        ],
      },
    },
    {
      version: "1.1.0",
      title: "[1.1.0] - 2019-02-15",
      date: "2019-02-15",
      body: "### Added\n\n- Danish translation.\n- Georgian translation from.\n- Changelog inconsistency section in Bad Practices.\n\n### Fixed\n\n- Italian translation.\n- Indonesian translation.",
      parsed: {
        _: [
          "Danish translation.",
          "Georgian translation from.",
          "Changelog inconsistency section in Bad Practices.",
          "Italian translation.",
          "Indonesian translation.",
        ],
        Added: [
          "Danish translation.",
          "Georgian translation from.",
          "Changelog inconsistency section in Bad Practices.",
        ],
        Fixed: ["Italian translation.", "Indonesian translation."],
      },
    },
    {
      version: "1.0.0",
      title: "[1.0.0] - 2017-06-20",
      date: "2017-06-20",
      body: '### Added\n\n- New visual identity by [@tylerfortune8].\n- Version navigation.\n- Links to latest released version in previous versions.\n- "Why keep a changelog?" section.\n- "Who needs a changelog?" section.\n- "How do I make a changelog?" section.\n- "Frequently Asked Questions" section.\n- New "Guiding Principles" sub-section to "How do I make a changelog?".\n- Simplified and Traditional Chinese translations from [@tianshuo].\n- German translation from [@mpbzh] & [@Art4].\n- Italian translation from [@azkidenz].\n- Swedish translation from [@magol].\n- Turkish translation from [@emreerkan].\n- French translation from [@zapashcanon].\n- Brazilian Portuguese translation from [@Webysther].\n- Polish translation from [@amielucha] & [@m-aciek].\n- Russian translation from [@aishek].\n- Czech translation from [@h4vry].\n- Slovak translation from [@jkostolansky].\n- Korean translation from [@pierceh89].\n- Croatian translation from [@porx].\n- Persian translation from [@Hameds].\n- Ukrainian translation from [@osadchyi-s].\n\n### Changed\n\n- Start using "changelog" over "change log" since it\'s the common usage.\n- Start versioning based on the current English version at 0.3.0 to help\n  translation authors keep things up-to-date.\n- Rewrite "What makes unicorns cry?" section.\n- Rewrite "Ignoring Deprecations" sub-section to clarify the ideal\n  scenario.\n- Improve "Commit log diffs" sub-section to further argument against\n  them.\n- Merge "Why can’t people just use a git log diff?" with "Commit log\n  diffs".\n- Fix typos in Simplified Chinese and Traditional Chinese translations.\n- Fix typos in Brazilian Portuguese translation.\n- Fix typos in Turkish translation.\n- Fix typos in Czech translation.\n- Fix typos in Swedish translation.\n- Improve phrasing in French translation.\n- Fix phrasing and spelling in German translation.\n\n### Removed\n\n- Section about "changelog" vs "CHANGELOG".',
      parsed: {
        _: [
          "New visual identity by @tylerfortune8.",
          "Version navigation.",
          "Links to latest released version in previous versions.",
          '"Why keep a changelog?" section.',
          '"Who needs a changelog?" section.',
          '"How do I make a changelog?" section.',
          '"Frequently Asked Questions" section.',
          'New "Guiding Principles" sub-section to "How do I make a changelog?".',
          "Simplified and Traditional Chinese translations from @tianshuo.",
          "German translation from @mpbzh & @Art4.",
          "Italian translation from @azkidenz.",
          "Swedish translation from @magol.",
          "Turkish translation from @emreerkan.",
          "French translation from @zapashcanon.",
          "Brazilian Portuguese translation from @Webysther.",
          "Polish translation from @amielucha & @m-aciek.",
          "Russian translation from @aishek.",
          "Czech translation from @h4vry.",
          "Slovak translation from @jkostolansky.",
          "Korean translation from @pierceh89.",
          "Croatian translation from @porx.",
          "Persian translation from @Hameds.",
          "Ukrainian translation from @osadchyi-s.",
          'Start using "changelog" over "change log" since it\'s the common usage.',
          "Start versioning based on the current English version at 0.3.0 to help",
          'Rewrite "What makes unicorns cry?" section.',
          'Rewrite "Ignoring Deprecations" sub-section to clarify the ideal',
          'Improve "Commit log diffs" sub-section to further argument against',
          'Merge "Why can’t people just use a git log diff?" with "Commit log',
          "Fix typos in Simplified Chinese and Traditional Chinese translations.",
          "Fix typos in Brazilian Portuguese translation.",
          "Fix typos in Turkish translation.",
          "Fix typos in Czech translation.",
          "Fix typos in Swedish translation.",
          "Improve phrasing in French translation.",
          "Fix phrasing and spelling in German translation.",
          'Section about "changelog" vs "CHANGELOG".',
        ],
        Added: [
          "New visual identity by @tylerfortune8.",
          "Version navigation.",
          "Links to latest released version in previous versions.",
          '"Why keep a changelog?" section.',
          '"Who needs a changelog?" section.',
          '"How do I make a changelog?" section.',
          '"Frequently Asked Questions" section.',
          'New "Guiding Principles" sub-section to "How do I make a changelog?".',
          "Simplified and Traditional Chinese translations from @tianshuo.",
          "German translation from @mpbzh & @Art4.",
          "Italian translation from @azkidenz.",
          "Swedish translation from @magol.",
          "Turkish translation from @emreerkan.",
          "French translation from @zapashcanon.",
          "Brazilian Portuguese translation from @Webysther.",
          "Polish translation from @amielucha & @m-aciek.",
          "Russian translation from @aishek.",
          "Czech translation from @h4vry.",
          "Slovak translation from @jkostolansky.",
          "Korean translation from @pierceh89.",
          "Croatian translation from @porx.",
          "Persian translation from @Hameds.",
          "Ukrainian translation from @osadchyi-s.",
        ],
        Changed: [
          'Start using "changelog" over "change log" since it\'s the common usage.',
          "Start versioning based on the current English version at 0.3.0 to help",
          'Rewrite "What makes unicorns cry?" section.',
          'Rewrite "Ignoring Deprecations" sub-section to clarify the ideal',
          'Improve "Commit log diffs" sub-section to further argument against',
          'Merge "Why can’t people just use a git log diff?" with "Commit log',
          "Fix typos in Simplified Chinese and Traditional Chinese translations.",
          "Fix typos in Brazilian Portuguese translation.",
          "Fix typos in Turkish translation.",
          "Fix typos in Czech translation.",
          "Fix typos in Swedish translation.",
          "Improve phrasing in French translation.",
          "Fix phrasing and spelling in German translation.",
        ],
        Removed: ['Section about "changelog" vs "CHANGELOG".'],
      },
    },
    {
      version: "0.3.0",
      title: "[0.3.0] - 2015-12-03",
      date: "2015-12-03",
      body: "### Added\n\n- RU translation from [@aishek].\n- pt-BR translation from [@tallesl].\n- es-ES translation from [@ZeliosAriex].",
      parsed: {
        _: [
          "RU translation from @aishek.",
          "pt-BR translation from @tallesl.",
          "es-ES translation from @ZeliosAriex.",
        ],
        Added: [
          "RU translation from @aishek.",
          "pt-BR translation from @tallesl.",
          "es-ES translation from @ZeliosAriex.",
        ],
      },
    },
    {
      version: "0.2.0",
      title: "[0.2.0] - 2015-10-06",
      date: "2015-10-06",
      body: '### Changed\n\n- Remove exclusionary mentions of "open source" since this project can\n  benefit both "open" and "closed" source projects equally.',
      parsed: {
        _: [
          'Remove exclusionary mentions of "open source" since this project can',
        ],
        Changed: [
          'Remove exclusionary mentions of "open source" since this project can',
        ],
      },
    },
    {
      version: "0.1.0",
      title: "[0.1.0] - 2015-10-06",
      date: "2015-10-06",
      body: '### Added\n\n- Answer "Should you ever rewrite a change log?".\n\n### Changed\n\n- Improve argument against commit logs.\n- Start following [SemVer] properly.',
      parsed: {
        _: [
          'Answer "Should you ever rewrite a change log?".',
          "Improve argument against commit logs.",
          "Start following SemVer properly.",
        ],
        Added: ['Answer "Should you ever rewrite a change log?".'],
        Changed: [
          "Improve argument against commit logs.",
          "Start following SemVer properly.",
        ],
      },
    },
    {
      version: "0.0.8",
      title: "[0.0.8] - 2015-02-17",
      date: "2015-02-17",
      body: "### Changed\n\n- Update year to match in every README example.\n- Reluctantly stop making fun of Brits only, since most of the world\n  writes dates in a strange way.\n\n### Fixed\n\n- Fix typos in recent README changes.\n- Update outdated unreleased diff link.",
      parsed: {
        _: [
          "Update year to match in every README example.",
          "Reluctantly stop making fun of Brits only, since most of the world",
          "Fix typos in recent README changes.",
          "Update outdated unreleased diff link.",
        ],
        Changed: [
          "Update year to match in every README example.",
          "Reluctantly stop making fun of Brits only, since most of the world",
        ],
        Fixed: [
          "Fix typos in recent README changes.",
          "Update outdated unreleased diff link.",
        ],
      },
    },
    {
      version: "0.0.7",
      title: "[0.0.7] - 2015-02-16",
      date: "2015-02-16",
      body: '### Added\n\n- Link, and make it obvious that date format is ISO 8601.\n\n### Changed\n\n- Clarified the section on "Is there a standard change log format?".\n\n### Fixed\n\n- Fix Markdown links to tag comparison URL with footnote-style links.',
      parsed: {
        _: [
          "Link, and make it obvious that date format is ISO 8601.",
          'Clarified the section on "Is there a standard change log format?".',
          "Fix Markdown links to tag comparison URL with footnote-style links.",
        ],
        Added: ["Link, and make it obvious that date format is ISO 8601."],
        Changed: [
          'Clarified the section on "Is there a standard change log format?".',
        ],
        Fixed: [
          "Fix Markdown links to tag comparison URL with footnote-style links.",
        ],
      },
    },
    {
      version: "0.0.6",
      title: "[0.0.6] - 2014-12-12",
      date: "2014-12-12",
      body: '### Added\n\n- README section on "yanked" releases.',
      parsed: {
        _: ['README section on "yanked" releases.'],
        Added: ['README section on "yanked" releases.'],
      },
    },
    {
      version: "0.0.5",
      title: "[0.0.5] - 2014-08-09",
      date: "2014-08-09",
      body: "### Added\n\n- Markdown links to version tags on release headings.\n- Unreleased section to gather unreleased changes and encourage note\n  keeping prior to releases.",
      parsed: {
        _: [
          "Markdown links to version tags on release headings.",
          "Unreleased section to gather unreleased changes and encourage note",
        ],
        Added: [
          "Markdown links to version tags on release headings.",
          "Unreleased section to gather unreleased changes and encourage note",
        ],
      },
    },
    {
      version: "0.0.4",
      title: "[0.0.4] - 2014-08-09",
      date: "2014-08-09",
      body: '### Added\n\n- Better explanation of the difference between the file ("CHANGELOG")\n  and its function "the change log".\n\n### Changed\n\n- Refer to a "change log" instead of a "CHANGELOG" throughout the site\n  to differentiate between the file and the purpose of the file — the\n  logging of changes.\n\n### Removed\n\n- Remove empty sections from CHANGELOG, they occupy too much space and\n  create too much noise in the file. People will have to assume that the\n  missing sections were intentionally left out because they contained no\n  notable changes.',
      parsed: {
        _: [
          'Better explanation of the difference between the file ("CHANGELOG")',
          'Refer to a "change log" instead of a "CHANGELOG" throughout the site',
          "Remove empty sections from CHANGELOG, they occupy too much space and",
        ],
        Added: [
          'Better explanation of the difference between the file ("CHANGELOG")',
        ],
        Changed: [
          'Refer to a "change log" instead of a "CHANGELOG" throughout the site',
        ],
        Removed: [
          "Remove empty sections from CHANGELOG, they occupy too much space and",
        ],
      },
    },
    {
      version: "0.0.3",
      title: "[0.0.3] - 2014-08-09",
      date: "2014-08-09",
      body: '### Added\n\n- "Why should I care?" section mentioning The Changelog podcast.',
      parsed: {
        _: ['"Why should I care?" section mentioning The Changelog podcast.'],
        Added: [
          '"Why should I care?" section mentioning The Changelog podcast.',
        ],
      },
    },
    {
      version: "0.0.2",
      title: "[0.0.2] - 2014-07-10",
      date: "2014-07-10",
      body: "### Added\n\n- Explanation of the recommended reverse chronological release ordering.",
      parsed: {
        _: [
          "Explanation of the recommended reverse chronological release ordering.",
        ],
        Added: [
          "Explanation of the recommended reverse chronological release ordering.",
        ],
      },
    },
    {
      version: "0.0.1",
      title: "[0.0.1] - 2014-05-31",
      date: "2014-05-31",
      body: '### Added\n\n- This CHANGELOG file to hopefully serve as an evolving example of a\n  standardized open source project CHANGELOG.\n- CNAME file to enable GitHub Pages custom domain.\n- README now contains answers to common questions about CHANGELOGs.\n- Good examples and basic guidelines, including proper date formatting.\n- Counter-examples: "What makes unicorns cry?".',
      parsed: {
        _: [
          "This CHANGELOG file to hopefully serve as an evolving example of a",
          "CNAME file to enable GitHub Pages custom domain.",
          "README now contains answers to common questions about CHANGELOGs.",
          "Good examples and basic guidelines, including proper date formatting.",
          'Counter-examples: "What makes unicorns cry?".',
        ],
        Added: [
          "This CHANGELOG file to hopefully serve as an evolving example of a",
          "CNAME file to enable GitHub Pages custom domain.",
          "README now contains answers to common questions about CHANGELOGs.",
          "Good examples and basic guidelines, including proper date formatting.",
          'Counter-examples: "What makes unicorns cry?".',
        ],
      },
    },
  ],
};

export default function ChangelogSectionDemo() {
  return <Changelog className="max-h-144 overflow-auto" document={changelog} />;
}
