import z from "zod";

const FeedSchema = z.object({
  publicationName: z.string().optional(),
  issn: z.string().optional(),
  eIssn: z.string().optional(),
  isbns: z.array(z.string()).optional(),
  issueIdentifier: z.string().optional(),
  issueName: z.string().optional(),
  issueTeaser: z.string().optional(),
  issueType: z.string().optional(),
  volume: z.string().optional(),
  number: z.string().optional(),
  edition: z.string().optional(),
  aggregateIssueNumber: z.number().optional(),
  aggregationType: z.string().optional(),
  coverDate: z.string().optional(),
  coverDisplayDate: z.string().optional(),
  publicationDates: z.array(z.string()).optional(),
  publicationDisplayDates: z.array(z.string()).optional(),
  creationDate: z.string().optional(),
  modificationDate: z.string().optional(),
  dateReceived: z.string().optional(),
  onSaleDates: z.array(z.string()).optional(),
  onSaleDays: z.array(z.string()).optional(),
  offSaleDates: z.array(z.string()).optional(),
  killDate: z.string().optional(),
  copyrightYears: z.array(z.string()).optional(),
  contentType: z.string().optional(),
  alternateTitles: z.array(z.string()).optional(),
  subtitles: z.array(z.string()).optional(),
  teasers: z.array(z.string()).optional(),
  keywords: z.array(z.string()).optional(),
  seriesTitle: z.string().optional(),
  seriesNumber: z.number().optional(),
  bookEditions: z.array(z.string()).optional(),
  nationalCatalogNumber: z.string().optional(),
  productCodes: z.array(z.string()).optional(),
  uspsNumber: z.string().optional(),
  publishingFrequency: z.string().optional(),
  channels: z.array(z.string()).optional(),
  subchannel1: z.string().optional(),
  subchannel2: z.string().optional(),
  subchannel3: z.string().optional(),
  subchannel4: z.string().optional(),
  section: z.string().optional(),
  subsection1: z.string().optional(),
  subsection2: z.string().optional(),
  subsection3: z.string().optional(),
  subsection4: z.string().optional(),
  corporateEntities: z.array(z.string()).optional(),
  distributor: z.string().optional(),
  sellingAgencies: z.array(z.string()).optional(),
  organizations: z.array(z.string()).optional(),
  persons: z.array(z.string()).optional(),
  platforms: z.array(z.string()).optional(),
  originPlatforms: z.array(z.string()).optional(),
  device: z.string().optional(),
  complianceProfile: z.string().optional(),
  blogTitle: z.string().optional(),
  blogURL: z.string().optional(),
  links: z.array(z.string()).optional(),
  urls: z.array(z.string()).optional(),
  byteCount: z.number().optional(),
  ratings: z.array(z.string()).optional(),
  timePeriod: z.string().optional(),
  versionIdentifier: z.string().optional(),
  tickers: z.array(z.string()).optional(),
  academicFields: z.array(z.string()).optional(),
  events: z.array(z.string()).optional(),
  genres: z.array(z.string()).optional(),
  industries: z.array(z.string()).optional(),
  locations: z.array(z.string()).optional(),
  objects: z.array(z.string()).optional(),
  profession: z.string().optional(),
  sport: z.string().optional(),
  embargoDate: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:embargoDate instead.",
  }),
  copyright: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:copyrightDate instead.",
  }),
  expirationDate: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:expirationDate instead.",
  }),
  rightsAgent: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:rightsAgent instead.",
  }),
});

const ItemSchema = z.object({
  publicationName: z.string().optional(),
  issn: z.string().optional(),
  eIssn: z.string().optional(),
  doi: z.string().optional(),
  urls: z.array(z.string()).optional(),
  volume: z.string().optional(),
  number: z.string().optional(),
  edition: z.string().optional(),
  section: z.string().optional(),
  startingPage: z.string().optional(),
  endingPage: z.string().optional(),
  pageRange: z.string().optional(),
  pageCount: z.number().optional(),
  pageProgressionDirection: z.string().optional(),
  samplePageRange: z.string().optional(),
  publicationDates: z.array(z.string()).optional(),
  publicationDisplayDates: z.array(z.string()).optional(),
  creationDate: z.string().optional(),
  modificationDate: z.string().optional(),
  dateReceived: z.string().optional(),
  killDate: z.string().optional(),
  copyrightYears: z.array(z.string()).optional(),
  contentType: z.string().optional(),
  genres: z.array(z.string()).optional(),
  alternateTitles: z.array(z.string()).optional(),
  subtitles: z.array(z.string()).optional(),
  teasers: z.array(z.string()).optional(),
  keywords: z.array(z.string()).optional(),
  corporateEntities: z.array(z.string()).optional(),
  organizations: z.array(z.string()).optional(),
  persons: z.array(z.string()).optional(),
  platforms: z.array(z.string()).optional(),
  device: z.string().optional(),
  academicFields: z.array(z.string()).optional(),
  events: z.array(z.string()).optional(),
  industries: z.array(z.string()).optional(),
  locations: z.array(z.string()).optional(),
  objects: z.array(z.string()).optional(),
  profession: z.string().optional(),
  sport: z.string().optional(),
  hasAlternatives: z.array(z.string()).optional(),
  hasCorrections: z.array(z.string()).optional(),
  hasTranslations: z.array(z.string()).optional(),
  isAlternativeOf: z.array(z.string()).optional(),
  isCorrectionOf: z.array(z.string()).optional(),
  isTranslationOf: z.string().optional(),
  supplementTitles: z.array(z.string()).optional(),
  supplementDisplayID: z.string().optional(),
  supplementStartingPage: z.string().optional(),
  links: z.array(z.string()).optional(),
  wordCount: z.number().optional(),
  byteCount: z.number().optional(),
  ratings: z.array(z.string()).optional(),
  timePeriod: z.string().optional(),
  versionIdentifier: z.string().optional(),
  tickers: z.array(z.string()).optional(),
  embargoDate: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:embargoDate instead.",
  }),
  copyright: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:copyrightDate instead.",
  }),
  expirationDate: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:expirationDate instead.",
  }),
  rightsAgent: z.string().optional().meta({
    deprecated: true,
    description: "Since PRISM 3.0. Use pur:rightsAgent instead.",
  }),
});

const PrismSchemas = {
  Feed: FeedSchema,
  Item: ItemSchema,
};

type Item = z.infer<typeof ItemSchema>;
type Feed = z.infer<typeof FeedSchema>;

declare namespace Prism {
  export type { Item, Feed };
}

export type { Feed, Item };
export { FeedSchema, ItemSchema, PrismSchemas };
